services:

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB=santa
    volumes:
      - ./MongoDB/mongodb-schema/:/docker-entrypoint-initdb.d/
      - mongo-data:/data/db

  flask-mongo:
    build: ./MongoDB/
    restart: always
    ports:
      - 5052:5052

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=santa
    volumes:
      - ./PostgreSQL/postgres-schema/:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5

  flask-postgres:
    depends_on:
      postgres:
        condition: service_healthy

    build: ./PostgreSQL/
    restart: always
    ports:
      - 5051:5051

volumes:
  mongo-data:
  postgres-data:
